scanner_configs:
  PythonOSV:
    exceptions:
      - advisory_id: CVE-2020-29651
        changed_by: security-team
        notes: Currently no patch exists and determined that this vulnerability is not exploitable.